name: CI/CD Multi-Services

on:
  push:
    branches: [ develop, main ]
  workflow_dispatch:
  repository_dispatch:
    types: [deploy-all, deploy-client, deploy-produit, deploy-commande]

permissions:
  contents: read
  packages: write
  actions: write

jobs:
  # Job pour service-client
  build-client:
    if: github.event_name == 'push' || github.event.action == 'deploy-all' || github.event.action == 'deploy-client'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: kuetcheal/service_client
          ref: develop
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build and test
        run: |
          mvn clean test
          mvn package -DskipTests

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/kuetcheal/service_client:${{ github.sha }} .
          docker tag ghcr.io/kuetcheal/service_client:${{ github.sha }} ghcr.io/kuetcheal/service_client:latest

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker push ghcr.io/kuetcheal/service_client:${{ github.sha }}
          docker push ghcr.io/kuetcheal/service_client:latest

      - name: Trigger other services
        if: github.event_name == 'push'
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: kuetcheal/service_produit
          event-type: deploy-all
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

  # Job pour service-produit
  build-produit:
    if: github.event.action == 'deploy-all' || github.event.action == 'deploy-produit'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: kuetcheal/service_produit
          ref: develop
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build and test
        run: |
          mvn clean test
          mvn package -DskipTests

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/kuetcheal/service_produit:${{ github.sha }} .
          docker tag ghcr.io/kuetcheal/service_produit:${{ github.sha }} ghcr.io/kuetcheal/service_produit:latest

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker push ghcr.io/kuetcheal/service_produit:${{ github.sha }}
          docker push ghcr.io/kuetcheal/service_produit:latest

      - name: Trigger service-commande
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: kuetcheal/service_commande
          event-type: deploy-all
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

  # Job pour service-commande
  build-commande:
    if: github.event.action == 'deploy-all' || github.event.action == 'deploy-commande'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: kuetcheal/service_commande
          ref: develop
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build and test
        run: |
          mvn clean test
          mvn package -DskipTests

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/kuetcheal/service_commande:${{ github.sha }} .
          docker tag ghcr.io/kuetcheal/service_commande:${{ github.sha }} ghcr.io/kuetcheal/service_commande:latest

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker push ghcr.io/kuetcheal/service_commande:${{ github.sha }}
          docker push ghcr.io/kuetcheal/service_commande:latest

  # Job de déploiement
  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [build-client, build-produit, build-commande]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        run: |
          echo "Deploying all services to production..."
          # Ici vous pouvez ajouter votre logique de déploiement
          # Par exemple : kubectl apply, docker-compose up, etc.
